def get_commands():
    return [
        "== Network Manager =="
        "nmcli device",
        "nmcli device wifi list",
        "== Interface ==",
        "iw dev",
        "iw list | grep -A 10 'Supported interface modes'",
        "iw wlan0 link",
        "== IP Address ==",
        "ip addr show uap0",
        "ip addr show wlan0",
        "== Status =="
        "so status hostapd",
        "so status dnsmasq",
        "sudo journalctl -xeu hostapd",
        "sudo journalctl -xeu dnsmasq",
        "sudo journalctl -xeu dhcpcd",
        "== Start ==",
        "so restart hostapd",
        "so restart dnsmasq",
        "== Configuration ==",
        "nano /etc/default/hostapd",
        "nano /etc/hostapd/hostapd.conf",
        "nano /etc/dnsmasq.conf",
        "nano /etc/network/interfaces",
        "nano /etc/dhcpcd.conf",
        "nano /etc/resolv.conf",
        "nano /etc/sysctl.conf",
        "nano /etc/NetworkManager/conf.d",
    ]